name: suno_samjho
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  url_launcher: ^6.3.0
  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.1.0
  flutter_tts: ^4.2.5
  uuid: ^4.0.0
  speech_to_text: ^7.0.0
  provider: ^6.1.1
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/logo.png
    - assets/mail.svg
    - assets/appleLogo.svg
    - assets/googleLogo.svg
    - assets/profile.svg
    - assets/password.svg
    - assets/onboardingPage_Img.png
    - assets/Shape.svg
    - assets/general_info.json
